### ISSUE TITLE
New custom object for user with user details stored in this custom object

### ISSUE THREAD

**Issue by Nikshit-Kapoor** [Indhuja-T/CWB-tool#19]

**Comment by Nikshit-Kapoor** [comment]
![Screenshot (181)](https://user-images.githubusercontent.com/49128009/124966059-70354480-e040-11eb-93ad-2835170e4ba1.png)
![Screenshot (182)](https://user-images.githubusercontent.com/49128009/124966067-73303500-e040-11eb-9a74-1c6f7acd4b25.png)
Completed saving user details to the custom user object, and further details filled by the user...

**Comment by Indhuja-T** [comment]
Completed the functionality
